name: svg_packer
description: Optimized and dynamic vector graphics for Flutter.
version: 0.1.0-pre.1
repository: https://github.com/aloisdeniel/svg_packer

environment:
  sdk: ^3.4.0

executables:
  svg_packer:

dependencies:
  vector_graphics_compiler: ^1.1.16
  vector_graphics_codec: ^1.1.13
  recase: ^4.1.0
  path: ^1.9.1
  args: ^2.7.0

dev_dependencies:
  lints: ^5.0.0
  test: ^1.24.0
