name: svg_packer
description: A sample command-line application.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.6.2

# Add regular dependencies here.
dependencies:
  vector_graphics_compiler: ^1.1.16
  vector_graphics_codec: ^1.1.13
  recase: ^4.1.0
  path: ^1.9.1
  args: ^2.7.0
  # path: ^1.8.0

dev_dependencies:
  lints: ^5.0.0
  test: ^1.24.0
